apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
#      - name: tensorboards-web-app
#        image: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
      - name: kubeflow-tensorboards-web-app-ppc64le
        image: quay.io/ibm/kubeflow-tensorboards-web-app-ppc64le
        ports:
        - containerPort: 5000
        env:
        - name: APP_PREFIX
          value: $(TWA_PREFIX)
        - name: USERID_HEADER
          value: $(TWA_USERID_HEADER)
        - name: USERID_PREFIX
          value: $(TWA_USERID_PREFIX)
      serviceAccountName: service-account
